### ISSUE TITLE
Verbetering: gebruik van classes

### ISSUE THREAD

**Issue by vangeest** [informatica-emmauscollege/1920-4V-LEERLING-GAME-amira-en-valentijn#3]
Valentijn,

Ik zie dat je je code voor de game hebt uitgebreid me een class. Op zich is een class in javascript een hele mooie constructie, maar hij past niet binnen het template van de game. Daarom in deze opdracht liever niet gebruiken, maar voortbouwen met functies en variabelen. Later op het vwo is er meer ruimte om object georienteerd te programmeren met classes.

Ik weet dat ik jou nu een beetje afrem, omdat je meer kunt, maar ik wil graag dat alle leerlingen een vergelijkbare opdracht inleveren. Er zijn binnen het template wel heel veel uitdagingen mogelijk. Je kunt bijvoorbeeld 3D gebruiken in je game. Op p5js.org staat een artikel over hoe 3D in p5js werkt (de link heb ik even niet bij de hand, als je het niet  kunt vinden, vraag het me).

Meneer Van Geest
gee@emmauscollege.nl

**Comment by Valentijnvw** [comment]
Ik heb de code omgeschreven en gebruik nu geen classes meer
